"""
Datos de Nexus: trivias, palabras e imágenes.

Cada pregunta es una tupla:
    (pregunta, respuesta_correcta, incorrecta1, incorrecta2, incorrecta3)
y opcionalmente un 6.º valor con el link directo de un GIF/imagen propio:
    (pregunta, correcta, mal1, mal2, mal3, "https://.../imagen.gif")

Si una pregunta no trae imagen propia, el bot usa las de IMAGENES[categoria]
(rotando entre ellas). Pega en IMAGENES tus links directos (.gif/.png/.jpg)
de Giphy, Tenor, Imgur, etc.
"""

IMAGENES = {
    "anime": [
        # "https://media.giphy.com/media/XXXX/giphy.gif",
    ],
    "historia": [
        # "https://i.imgur.com/XXXX.png",
    ],
    "videojuegos": [
        # "https://media.giphy.com/media/YYYY/giphy.gif",
    ],
}

ANIME = [
    ("¿Cómo se llama el protagonista de Naruto?", "Naruto Uzumaki", "Sasuke Uchiha", "Kakashi Hatake", "Minato Namikaze"),
    ("¿Quién es el capitán de los Piratas de Sombrero de Paja?", "Monkey D. Luffy", "Roronoa Zoro", "Sanji", "Portgas D. Ace"),
    ("¿Cómo se llama el protagonista de Death Note?", "Light Yagami", "L", "Ryuk", "Near"),
    ("¿Cuántas Esferas del Dragón hay que reunir para invocar a Shenlong?", "7", "5", "9", "12"),
    ("¿Cómo se llama el hermano menor de Edward Elric?", "Alphonse", "Roy", "Winry", "Maes"),
    ("¿Qué Pokémon es el compañero inseparable de Ash?", "Pikachu", "Charmander", "Eevee", "Togepi"),
    ("¿Qué titán heredó Eren Jaeger al inicio de Attack on Titan?", "Titán Atacante", "Titán Colosal", "Titán Acorazado", "Titán Bestia"),
    ("¿Cómo se llama la hermana de Tanjiro en Demon Slayer?", "Nezuko", "Shinobu", "Mitsuri", "Kanao"),
    ("¿De qué raza es Goku?", "Saiyajin", "Namekiano", "Humano", "Majin"),
    ("¿Quién es el autor de One Piece?", "Eiichiro Oda", "Masashi Kishimoto", "Akira Toriyama", "Tite Kubo"),
    ("¿Qué estudio creó El viaje de Chihiro?", "Studio Ghibli", "Toei Animation", "MAPPA", "Madhouse"),
    ("¿Qué Hokage selló al Kyubi dentro de Naruto y murió?", "Minato Namikaze", "Hiruzen Sarutobi", "Tobirama Senju", "Hashirama Senju"),
    ("¿Cuál es el principio básico de la alquimia en Fullmetal Alchemist?", "Intercambio equivalente", "Transmutación humana", "Piedra filosofal", "Conservación de la energía"),
    ("¿Cómo se llama el protagonista de My Hero Academia?", "Izuku Midoriya", "Katsuki Bakugo", "Shoto Todoroki", "Tenya Iida"),
    ("¿Quién fue el Rey de los Piratas antes de Luffy?", "Gol D. Roger", "Barbablanca", "Shanks", "Kaido"),
    ("¿Cómo se llama el protagonista de Sword Art Online?", "Kirito", "Asuna", "Klein", "Sinon"),
    ("¿Qué shinigami ama las manzanas en Death Note?", "Ryuk", "Rem", "Gelus", "Sidoh"),
    ("¿Cómo se llama la zanpakuto de Ichigo en Bleach?", "Zangetsu", "Senbonzakura", "Hyorinmaru", "Benihime"),
    ("¿Quién es el mejor amigo de Gon en Hunter x Hunter?", "Killua", "Kurapika", "Leorio", "Hisoka"),
    ("¿De qué película es el espíritu del bosque Totoro?", "Mi vecino Totoro", "La princesa Mononoke", "Ponyo", "Nicky, la aprendiz de bruja"),
    ("¿Quién es considerado el soldado más fuerte de la humanidad en Attack on Titan?", "Levi Ackerman", "Erwin Smith", "Mikasa Ackerman", "Jean Kirstein"),
    ("¿Cómo se llama la técnica icónica de Goku?", "Kamehameha", "Rasengan", "Chidori", "Getsuga Tenshō"),
    ("¿Cómo se llama la esfera de chakra giratoria que usa Naruto?", "Rasengan", "Chidori", "Amaterasu", "Kirin"),
    ("¿Cómo se llama la academia de héroes de My Hero Academia?", "U.A.", "Shiketsu", "Seiai", "Ketsubutsu"),
    ("¿Quién es el protagonista de Cowboy Bebop?", "Spike Spiegel", "Jet Black", "Faye Valentine", "Vicious"),
    ("¿Cómo se llama el hermano mayor de Sasuke?", "Itachi", "Madara", "Obito", "Shisui"),
    ("¿A qué organización criminal perteneció Itachi?", "Akatsuki", "Los Cuatro del Sonido", "Raíz", "Los Siete Espadachines"),
    ("¿Cómo se llama el hijo mayor de Goku?", "Gohan", "Goten", "Trunks", "Pan"),
    ("¿Cómo se llama el príncipe de los Saiyajin?", "Vegeta", "Bardock", "Raditz", "Nappa"),
    ("¿Cómo se llama el protagonista de Neon Genesis Evangelion?", "Shinji Ikari", "Rei Ayanami", "Asuka Langley", "Kaworu Nagisa"),
    ("¿Qué anime sigue a un club de música ligera con Yui y Mio?", "K-On!", "Bocchi the Rock!", "Love Live!", "Nana"),
    ("¿Cómo se llama la protagonista de Bocchi the Rock!?", "Hitori Gotoh", "Nijika Ijichi", "Ryo Yamada", "Ikuyo Kita"),
    ("¿Cómo se llama el protagonista de Jujutsu Kaisen?", "Yuji Itadori", "Megumi Fushiguro", "Satoru Gojo", "Nobara Kugisaki"),
    ("¿Qué maldición vive dentro de Yuji Itadori?", "Ryomen Sukuna", "Mahito", "Jogo", "Suguru Geto"),
    ("¿Quién es el maestro de Naruto apodado 'el ninja que copia'?", "Kakashi Hatake", "Jiraiya", "Iruka Umino", "Might Guy"),
    ("¿Cómo se llama el cocinero de los Sombrero de Paja?", "Sanji", "Usopp", "Franky", "Brook"),
    ("¿Cómo se llama el reno doctor de los Sombrero de Paja?", "Tony Tony Chopper", "Nami", "Nico Robin", "Jinbe"),
    ("¿Qué anime tiene al Imperio de Britannia y a Lelouch?", "Code Geass", "Gundam", "Fate/Zero", "Steins;Gate"),
    ("¿Cómo se llama el protagonista de Steins;Gate?", "Rintaro Okabe", "Kurisu Makise", "Mayuri Shiina", "Itaru Hashida"),
    ("¿Cómo se llaman las espadas que usan los cazadores de Demon Slayer?", "Espadas Nichirin", "Zanpakuto", "Excalibur", "Masamune"),
    ("¿Qué estilo de respiración usa principalmente Tanjiro?", "Respiración del Agua", "Respiración del Trueno", "Respiración de la Llama", "Respiración del Viento"),
    ("¿Quién es el Pilar de la Llama en Demon Slayer?", "Kyojuro Rengoku", "Giyu Tomioka", "Tengen Uzui", "Muichiro Tokito"),
    ("¿Cómo se llama el protagonista de Black Clover?", "Asta", "Yuno", "Noelle Silva", "Yami Sukehiro"),
    ("¿Cómo se llama la protagonista de Sailor Moon?", "Usagi Tsukino", "Ami Mizuno", "Rei Hino", "Minako Aino"),
    ("¿Cómo se llama la gata parlante de Sailor Moon?", "Luna", "Artemis", "Diana", "Kero"),
    ("¿Quién es el autor de Dragon Ball?", "Akira Toriyama", "Eiichiro Oda", "Hajime Isayama", "Yoshihiro Togashi"),
    ("¿Cómo se llama el protagonista de One Punch Man?", "Saitama", "Genos", "Garou", "Mumen Rider"),
    ("¿Cómo se llama el discípulo cyborg de Saitama?", "Genos", "Sonic el Veloz", "Bang", "Tatsumaki"),
    ("¿Qué perdió Edward Elric en su transmutación humana?", "Un brazo y una pierna", "Los ojos", "La voz", "La memoria"),
    ("¿En qué anime existen los 'Stands'?", "JoJo's Bizarre Adventure", "Hunter x Hunter", "Fairy Tail", "Tokyo Ghoul"),
    ("¿Quién es el protagonista de JoJo's Stardust Crusaders?", "Jotaro Kujo", "Joseph Joestar", "Josuke Higashikata", "Giorno Giovanna"),
    ("¿Cómo se llama el Stand de Dio en Stardust Crusaders?", "The World", "Star Platinum", "Crazy Diamond", "Gold Experience"),
    ("¿Cómo se llama el protagonista de Tokyo Ghoul?", "Ken Kaneki", "Touka Kirishima", "Renji Yomo", "Juuzou Suzuya"),
    ("¿Cómo se llama el protagonista de Fairy Tail?", "Natsu Dragneel", "Gray Fullbuster", "Erza Scarlet", "Lucy Heartfilia"),
    ("¿Cómo se llama el gato azul que acompaña a Natsu?", "Happy", "Plue", "Lector", "Frosch"),
    ("¿Cómo se llama el protagonista de Haikyuu!!?", "Shoyo Hinata", "Tobio Kageyama", "Kei Tsukishima", "Tetsuro Kuroo"),
    ("¿Qué deporte se practica en Haikyuu!!?", "Voleibol", "Baloncesto", "Béisbol", "Tenis"),
    ("¿Qué deporte se practica en Slam Dunk?", "Baloncesto", "Fútbol", "Voleibol", "Béisbol"),
    ("¿Cómo se llama el protagonista de Supercampeones (Captain Tsubasa)?", "Tsubasa Ozora", "Kojiro Hyuga", "Genzo Wakabayashi", "Taro Misaki"),
    ("¿Cómo se llama el protagonista de Kuroko no Basket?", "Tetsuya Kuroko", "Taiga Kagami", "Daiki Aomine", "Seijuro Akashi"),
    ("¿Cómo se llaman los robots gigantes de Neon Genesis Evangelion?", "Unidades EVA", "Gundam", "Mazinger Z", "Gurren Lagann"),
    ("¿Quién es el protagonista de Gurren Lagann?", "Simon", "Kamina", "Viral", "Yoko"),
    ("¿Cómo se llama la niña telépata de Spy x Family?", "Anya Forger", "Yor Forger", "Becky Blackbell", "Fiona Frost"),
    ("¿Qué comida es la favorita de Anya en Spy x Family?", "Cacahuates", "Pizza", "Dulces", "Ramen"),
    ("¿Cómo se llama el perro de la familia Forger?", "Bond", "Rex", "Max", "Pochi"),
    ("¿Cómo se llama la protagonista de Violet Evergarden?", "Violet Evergarden", "Cattleya Baudelaire", "Iris Cannary", "Erica Brown"),
    ("¿Quién es el autor de Attack on Titan?", "Hajime Isayama", "Kohei Horikoshi", "Gege Akutami", "Tatsuki Fujimoto"),
    ("¿Quién es el autor de Chainsaw Man?", "Tatsuki Fujimoto", "Yuki Tabata", "Sui Ishida", "Koyoharu Gotouge"),
    ("¿Cómo se llama el protagonista de Chainsaw Man?", "Denji", "Aki Hayakawa", "Power", "Kobeni"),
    ("¿Cómo se llama el demonio motosierra mascota de Denji?", "Pochita", "Beam", "Kon", "Meowy"),
    ("¿Cómo se llama el protagonista de Re:Zero?", "Subaru Natsuki", "Kazuma Sato", "Rimuru Tempest", "Ainz Ooal Gown"),
    ("¿Cómo se llama el protagonista de Tensei Shitara Slime Datta Ken?", "Rimuru Tempest", "Veldora", "Milim Nava", "Benimaru"),
    ("¿Cómo se llama la maga de las explosiones en KonoSuba?", "Megumin", "Aqua", "Darkness", "Yunyun"),
    ("¿Cómo se llama el protagonista de Overlord?", "Ainz Ooal Gown", "Albedo", "Demiurge", "Shalltear"),
    ("¿Cómo se llama el protagonista de Mob Psycho 100?", "Shigeo Kageyama", "Reigen Arataka", "Teruki Hanazawa", "Ritsu Kageyama"),
    ("¿Cómo se llama la expansión de dominio de Gojo Satoru?", "Vacío Ilimitado", "Santuario Malévolo", "Cámara de la Muerte Ardiente", "Sombra Quimérica"),
    ("¿Cómo se llama el pirata que le dio su sombrero a Luffy?", "Shanks", "Buggy", "Eustass Kid", "Marco"),
    ("¿Qué fruta del diablo comió Luffy?", "Gomu Gomu no Mi", "Mera Mera no Mi", "Hito Hito no Mi", "Yami Yami no Mi"),
    ("¿Cómo se llama el barco de los Sombrero de Paja que sucedió al Going Merry?", "Thousand Sunny", "Moby Dick", "Red Force", "Polar Tang"),
    ("¿Qué personaje de One Piece usa tres espadas?", "Roronoa Zoro", "Mihawk", "Smoker", "Trafalgar Law"),
    ("¿Quién es la navegante de los Sombrero de Paja?", "Nami", "Nico Robin", "Vivi", "Boa Hancock"),
    ("¿Cómo se llama el protagonista de Dr. Stone?", "Senku Ishigami", "Taiju Oki", "Tsukasa Shishio", "Chrome"),
    ("¿Cómo se llama la protagonista de Kaguya-sama: Love is War?", "Kaguya Shinomiya", "Chika Fujiwara", "Miko Iino", "Ai Hayasaka"),
    ("¿Cómo se llama el protagonista masculino de Your Name (Kimi no Na wa)?", "Taki Tachibana", "Shinji Ikari", "Hotaka Mimura", "Souta Munakata"),
    ("¿Quién dirigió Your Name (Kimi no Na wa)?", "Makoto Shinkai", "Hayao Miyazaki", "Mamoru Hosoda", "Satoshi Kon"),
    ("¿Quién dirigió El viaje de Chihiro?", "Hayao Miyazaki", "Isao Takahata", "Makoto Shinkai", "Hideaki Anno"),
    ("¿Quién creó Neon Genesis Evangelion?", "Hideaki Anno", "Hayao Miyazaki", "Shinichiro Watanabe", "Satoshi Kon"),
    ("¿Cómo se llama el protagonista de Akira?", "Shotaro Kaneda", "Tetsuo Shima", "Kei", "Coronel Shikishima"),
    ("¿Cómo se llama la protagonista de Cardcaptor Sakura?", "Sakura Kinomoto", "Sakura Haruno", "Sakura Kasugano", "Sakura Matou"),
    ("¿Cómo se llama la chica que viaja al pasado en Inuyasha?", "Kagome Higurashi", "Kikyo", "Sango", "Rin"),
    ("¿Cuántos Pokémon iniciales hay en la primera generación?", "3", "2", "4", "5"),
    ("¿Cómo se llama el rival de Ash en Kanto?", "Gary Oak", "Brock", "Paul", "Misty"),
    ("¿Cómo se llama el protagonista de Digimon Adventure?", "Tai Kamiya", "Matt Ishida", "Izzy Izumi", "Joe Kido"),
    ("¿Cómo se llama el Digimon de Tai?", "Agumon", "Gabumon", "Patamon", "Gomamon"),
    ("¿Cómo se llama la protagonista de Madoka Magica?", "Madoka Kaname", "Homura Akemi", "Sayaka Miki", "Mami Tomoe"),
    ("¿Qué criatura ofrece contratos a las chicas en Madoka Magica?", "Kyubey", "Luna", "Mokona", "Kero"),
    ("¿Qué anime tiene al 'Nen' como sistema de poder?", "Hunter x Hunter", "Naruto", "Bleach", "Dragon Ball"),
    ("¿Cómo se llama el protagonista de Vinland Saga?", "Thorfinn", "Askeladd", "Thorkell", "Canute"),
]

HISTORIA = [
    ("¿En qué año llegó Colón a América?", "1492", "1500", "1453", "1521"),
    ("¿En qué año comenzó la Revolución Francesa?", "1789", "1776", "1804", "1815"),
    ("¿Quién fue el primer presidente de Estados Unidos?", "George Washington", "Thomas Jefferson", "Abraham Lincoln", "John Adams"),
    ("¿En qué año terminó la Segunda Guerra Mundial?", "1945", "1939", "1918", "1950"),
    ("¿Qué civilización construyó las pirámides de Giza?", "Egipcia", "Maya", "Romana", "Griega"),
    ("¿A qué isla fue exiliado Napoleón tras Waterloo?", "Santa Elena", "Elba", "Córcega", "Malta"),
    ("¿En qué año cayó el Muro de Berlín?", "1989", "1991", "1961", "1975"),
    ("¿Qué ciudad era el centro del imperio que gobernó Julio César?", "Roma", "Atenas", "Cartago", "Alejandría"),
    ("¿Quién lideró la independencia de Venezuela, Colombia, Ecuador, Perú y Bolivia?", "Simón Bolívar", "José de San Martín", "Miguel Hidalgo", "Benito Juárez"),
    ("¿En qué año inició la guerra de independencia de México con el Grito de Dolores?", "1810", "1821", "1789", "1846"),
    ("¿Quién fue el líder de la Alemania nazi?", "Adolf Hitler", "Benito Mussolini", "Francisco Franco", "Iósif Stalin"),
    ("¿En qué año ocurrió el ataque a Pearl Harbor?", "1941", "1939", "1944", "1937"),
    ("¿Qué civilización construyó Machu Picchu?", "Inca", "Azteca", "Maya", "Olmeca"),
    ("¿Cuál era la capital del Imperio azteca?", "Tenochtitlan", "Cusco", "Teotihuacan", "Tikal"),
    ("¿Quién conquistó el Imperio azteca?", "Hernán Cortés", "Francisco Pizarro", "Pedro de Valdivia", "Vasco Núñez de Balboa"),
    ("¿Quién conquistó el Imperio inca?", "Francisco Pizarro", "Hernán Cortés", "Diego de Almagro", "Pedro de Alvarado"),
    ("¿En qué año se hundió el Titanic?", "1912", "1905", "1920", "1898"),
    ("¿Cómo se llamó la guerra entre el Norte y el Sur de Estados Unidos (1861-1865)?", "Guerra de Secesión", "Guerra de Independencia", "Guerra de 1812", "Guerra Fría"),
    ("¿Qué reina gobernaba Inglaterra cuando fue derrotada la Armada Invencible en 1588?", "Isabel I", "Victoria", "María I", "Ana"),
    ("¿Qué conflicto comenzó en 1914?", "Primera Guerra Mundial", "Segunda Guerra Mundial", "Guerra Fría", "Guerra de Corea"),
    ("¿Quién fue el primer hombre en pisar la Luna?", "Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Michael Collins"),
    ("¿En qué año llegó el ser humano a la Luna?", "1969", "1961", "1972", "1957"),
    ("¿Quién fue el primer ser humano en viajar al espacio?", "Yuri Gagarin", "Neil Armstrong", "Alan Shepard", "John Glenn"),
    ("¿Qué imperio tenía por capital Constantinopla?", "Bizantino", "Romano de Occidente", "Persa", "Mongol"),
    ("¿En qué año cayó Constantinopla en manos otomanas?", "1453", "1492", "1204", "1517"),
    ("¿Quién fundó el Imperio mongol?", "Gengis Kan", "Atila", "Tamerlán", "Kublai Kan"),
    ("¿Qué guerra duró de 1337 a 1453?", "Guerra de los Cien Años", "Guerra de las Dos Rosas", "Guerra de los Treinta Años", "Guerra de Sucesión Española"),
    ("¿Qué faraón niño tiene una famosa tumba hallada por Howard Carter?", "Tutankamón", "Ramsés II", "Keops", "Akenatón"),
    ("¿Qué tipo de escritura usaban los antiguos egipcios?", "Jeroglífica", "Cuneiforme", "Rúnica", "Latina"),
    ("¿Qué civilización inventó la escritura cuneiforme?", "Sumeria", "Egipcia", "China", "Fenicia"),
    ("¿En qué lugar se celebraron los primeros Juegos Olímpicos de la Antigüedad?", "Olimpia", "Atenas", "Esparta", "Delfos"),
    ("¿Quién fue el maestro del filósofo Platón?", "Sócrates", "Aristóteles", "Pitágoras", "Heráclito"),
    ("¿Quién fue el maestro de Alejandro Magno?", "Aristóteles", "Platón", "Sócrates", "Epicuro"),
    ("¿Qué rey macedonio conquistó el Imperio persa?", "Alejandro Magno", "Filipo II", "Pericles", "Leónidas"),
    ("¿Qué ciudad fue sepultada por la erupción del Vesubio en el año 79?", "Pompeya", "Roma", "Atenas", "Cartago"),
    ("¿Qué general cartaginés cruzó los Alpes con elefantes?", "Aníbal", "Escipión", "Asdrúbal", "Pirro"),
    ("¿En qué año cayó el Imperio romano de Occidente?", "476", "395", "1453", "800"),
    ("¿Quién fue el primer emperador romano?", "Augusto", "Julio César", "Nerón", "Constantino"),
    ("¿Qué emperador romano promulgó el Edicto de Milán a favor de los cristianos?", "Constantino", "Nerón", "Trajano", "Diocleciano"),
    ("¿Qué documento firmó el rey Juan de Inglaterra en 1215?", "Carta Magna", "Declaración de Derechos", "Petición de Derechos", "Acta de Unión"),
    ("¿Quién inició la Reforma protestante en 1517?", "Martín Lutero", "Juan Calvino", "Erasmo de Róterdam", "Enrique VIII"),
    ("¿Quién inventó la imprenta de tipos móviles en Europa?", "Johannes Gutenberg", "Leonardo da Vinci", "Galileo Galilei", "Nicolás Copérnico"),
    ("¿Quién completó la primera vuelta al mundo tras la muerte de Magallanes?", "Juan Sebastián Elcano", "Cristóbal Colón", "Vasco da Gama", "Pedro Álvares Cabral"),
    ("¿Qué navegante portugués llegó a la India por mar en 1498?", "Vasco da Gama", "Fernando de Magallanes", "Bartolomeu Dias", "Pedro Álvares Cabral"),
    ("¿A qué territorio llegó Pedro Álvares Cabral en 1500?", "Brasil", "Argentina", "Perú", "México"),
    ("¿En qué año se firmó la Declaración de Independencia de Estados Unidos?", "1776", "1789", "1812", "1865"),
    ("¿Quién era presidente de Estados Unidos durante la Guerra de Secesión?", "Abraham Lincoln", "Ulysses Grant", "Andrew Jackson", "Theodore Roosevelt"),
    ("¿Qué presidente estadounidense fue asesinado en Dallas en 1963?", "John F. Kennedy", "Abraham Lincoln", "Ronald Reagan", "James Garfield"),
    ("¿Qué crisis de 1962 casi provoca una guerra nuclear entre EE. UU. y la URSS?", "Crisis de los misiles de Cuba", "Bloqueo de Berlín", "Guerra de Corea", "Crisis de Suez"),
    ("¿Quién lideró la Revolución cubana de 1959?", "Fidel Castro", "Che Guevara", "Fulgencio Batista", "Camilo Cienfuegos"),
    ("¿Quién fue el líder bolchevique de la Revolución rusa de 1917?", "Vladímir Lenin", "Iósif Stalin", "León Trotski", "Nicolás II"),
    ("¿Quién fue el último zar de Rusia?", "Nicolás II", "Pedro el Grande", "Alejandro II", "Iván el Terrible"),
    ("¿Qué líder indio promovió la resistencia no violenta?", "Mahatma Gandhi", "Jawaharlal Nehru", "Muhammad Ali Jinnah", "Subhas Chandra Bose"),
    ("¿Qué líder sudafricano pasó 27 años preso y luego fue presidente?", "Nelson Mandela", "Desmond Tutu", "Thabo Mbeki", "Steve Biko"),
    ("¿Qué país lanzó las bombas atómicas sobre Hiroshima y Nagasaki?", "Estados Unidos", "Alemania", "Unión Soviética", "Reino Unido"),
    ("¿En qué año se lanzó la bomba atómica sobre Hiroshima?", "1945", "1941", "1950", "1939"),
    ("¿Qué tratado puso fin a la Primera Guerra Mundial con Alemania?", "Tratado de Versalles", "Tratado de Tordesillas", "Tratado de Utrecht", "Paz de Westfalia"),
    ("¿Qué tratado dividió el Nuevo Mundo entre España y Portugal en 1494?", "Tratado de Tordesillas", "Tratado de Versalles", "Tratado de Utrecht", "Paz de Westfalia"),
    ("¿Qué día fue el Desembarco de Normandía?", "6 de junio de 1944", "7 de diciembre de 1941", "8 de mayo de 1945", "1 de septiembre de 1939"),
    ("¿Cómo se llamó la tensión entre EE. UU. y la URSS sin enfrentamiento directo?", "Guerra Fría", "Guerra de los Seis Días", "Guerra de Vietnam", "Guerra del Golfo"),
    ("¿Quién gobernó la Unión Soviética tras la muerte de Lenin?", "Iósif Stalin", "Nikita Jrushchov", "Leonid Brézhnev", "Mijaíl Gorbachov"),
    ("¿Quién fue el último líder de la Unión Soviética?", "Mijaíl Gorbachov", "Borís Yeltsin", "Leonid Brézhnev", "Yuri Andropov"),
    ("¿En qué año se disolvió la Unión Soviética?", "1991", "1989", "1985", "2000"),
    ("¿Qué civilización construyó el Partenón?", "Griega", "Romana", "Persa", "Fenicia"),
    ("¿Qué ciudad-estado griega era famosa por sus guerreros?", "Esparta", "Atenas", "Corinto", "Tebas"),
    ("¿Quién fue el primer emperador de la China unificada?", "Qin Shi Huang", "Kublai Kan", "Sun Yat-sen", "Mao Zedong"),
    ("¿Qué dinastía construyó la mayor parte de la Gran Muralla que se conserva hoy?", "Ming", "Han", "Tang", "Qing"),
    ("¿Quién llegó a Norteamérica alrededor del año 1000?", "Leif Erikson", "Cristóbal Colón", "Américo Vespucio", "John Cabot"),
    ("¿Qué epidemia mató a gran parte de Europa en el siglo XIV?", "Peste Negra", "Viruela", "Gripe española", "Cólera"),
    ("¿Qué pandemia ocurrió entre 1918 y 1920?", "Gripe española", "Peste negra", "Tifus", "Polio"),
    ("¿Qué heroína francesa fue quemada en la hoguera en 1431?", "Juana de Arco", "María Antonieta", "Catalina de Médici", "Leonor de Aquitania"),
    ("¿Qué rey de Francia fue guillotinado en 1793?", "Luis XVI", "Luis XIV", "Carlos X", "Luis XV"),
    ("¿Qué rey francés era llamado 'el Rey Sol'?", "Luis XIV", "Luis XVI", "Napoleón III", "Enrique IV"),
    ("¿Qué batalla puso fin al dominio de Napoleón en 1815?", "Waterloo", "Trafalgar", "Austerlitz", "Borodinó"),
    ("¿Qué almirante británico murió en la batalla de Trafalgar?", "Horatio Nelson", "Duque de Wellington", "Francis Drake", "James Cook"),
    ("¿Qué líder militar encabezó a los 'Camisas Rojas' en la unificación italiana?", "Giuseppe Garibaldi", "Benito Mussolini", "Camillo Cavour", "Víctor Manuel II"),
    ("¿Qué canciller unificó Alemania en 1871?", "Otto von Bismarck", "Adolf Hitler", "Federico el Grande", "Konrad Adenauer"),
    ("¿Qué reina gobernó el Reino Unido durante 63 años en el siglo XIX?", "Victoria", "Isabel II", "Ana", "María Tudor"),
    ("¿Qué revolución comenzó en Gran Bretaña en el siglo XVIII?", "Revolución Industrial", "Revolución Gloriosa", "Revolución Francesa", "Revolución Verde"),
    ("¿Qué inventor perfeccionó la máquina de vapor?", "James Watt", "Thomas Edison", "Nikola Tesla", "Benjamin Franklin"),
    ("¿Quién descubrió la penicilina?", "Alexander Fleming", "Louis Pasteur", "Marie Curie", "Robert Koch"),
    ("¿Quién propuso la teoría heliocéntrica en el Renacimiento?", "Nicolás Copérnico", "Ptolomeo", "Aristóteles", "Tycho Brahe"),
    ("¿Qué científico fue juzgado por la Inquisición por defender el heliocentrismo?", "Galileo Galilei", "Isaac Newton", "Johannes Kepler", "Leonardo da Vinci"),
    ("¿En qué país nació la democracia?", "Grecia", "Roma", "Egipto", "Francia"),
    ("¿Qué imperio tenía a Moctezuma como emperador?", "Azteca", "Inca", "Maya", "Mongol"),
    ("¿Qué civilización desarrolló un famoso calendario y habitó la península de Yucatán?", "Maya", "Inca", "Azteca", "Tolteca"),
    ("¿Quién fue la última reina del Antiguo Egipto ptolemaico?", "Cleopatra VII", "Nefertiti", "Hatshepsut", "Nefertari"),
    ("¿Qué país gobernó Francisco Franco?", "España", "Portugal", "Italia", "Argentina"),
    ("¿Qué dictador italiano fue aliado de Hitler?", "Benito Mussolini", "Francisco Franco", "António Salazar", "Josip Broz Tito"),
    ("¿Qué ocurrió el 11 de septiembre de 2001?", "Ataques a las Torres Gemelas", "Caída del Muro de Berlín", "Guerra del Golfo", "Atentado de Madrid"),
    ("¿Qué guerra enfrentó a Estados Unidos con Vietnam del Norte?", "Guerra de Vietnam", "Guerra de Corea", "Guerra del Golfo", "Guerra de Irak"),
    ("¿Qué país fue dividido tras la Segunda Guerra Mundial y reunificado en 1990?", "Alemania", "Corea", "Vietnam", "Polonia"),
    ("¿Qué barco llevó a los Peregrinos a Norteamérica en 1620?", "Mayflower", "Santa María", "Titanic", "Beagle"),
    ("¿Cómo se llamaba la nao insignia de Cristóbal Colón en 1492?", "Santa María", "Pinta", "Niña", "San Martín"),
    ("¿Qué cultura preincaica creó las famosas líneas del desierto de Perú?", "Nazca", "Maya", "Olmeca", "Inca"),
    ("¿Qué cultura es considerada la 'cultura madre' de Mesoamérica?", "Olmeca", "Azteca", "Maya", "Zapoteca"),
    ("¿Quién lideró la División del Norte en la Revolución mexicana?", "Francisco 'Pancho' Villa", "Emiliano Zapata", "Porfirio Díaz", "Venustiano Carranza"),
    ("¿Quién fue el caudillo del sur en la Revolución mexicana?", "Emiliano Zapata", "Francisco Villa", "Francisco I. Madero", "Álvaro Obregón"),
    ("¿Qué país fue el primero en conceder el voto a las mujeres a nivel nacional en 1893?", "Nueva Zelanda", "Estados Unidos", "Reino Unido", "Francia"),
]

VIDEOJUEGOS = [
    ("¿Cómo se llama el fontanero más famoso de Nintendo?", "Mario", "Luigi", "Wario", "Yoshi"),
    ("¿Cómo se llama la princesa que Mario suele rescatar?", "Peach", "Zelda", "Daisy", "Rosalina"),
    ("¿Quién es el héroe de la saga The Legend of Zelda?", "Link", "Zelda", "Ganon", "Epona"),
    ("¿Cómo se llama el erizo azul de Sega?", "Sonic", "Tails", "Knuckles", "Shadow"),
    ("¿Qué estudio creó Pokémon?", "Game Freak", "Capcom", "Square Enix", "Konami"),
    ("¿Cómo se llama el protagonista de Halo?", "Jefe Maestro", "Marcus Fenix", "Doomguy", "Gordon Freeman"),
    ("¿En qué juego aparecen los Creepers?", "Minecraft", "Roblox", "Terraria", "Fortnite"),
    ("¿Qué juego popularizó el 'Bus de batalla' con globo aerostático?", "Fortnite", "Free Fire", "Apex Legends", "PUBG"),
    ("¿Cuál es el videojuego más vendido de la historia?", "Minecraft", "Tetris", "GTA V", "Wii Sports"),
    ("¿Qué estudio creó Minecraft?", "Mojang", "Epic Games", "Riot Games", "Blizzard"),
    ("¿Quién es el villano principal de Super Mario Bros.?", "Bowser", "Wario", "Ganondorf", "Dr. Eggman"),
    ("¿Cómo se llama el villano principal de Sonic?", "Dr. Eggman", "Bowser", "Ganon", "Sephiroth"),
    ("¿Cómo se llama el protagonista de Final Fantasy VII?", "Cloud Strife", "Squall Leonhart", "Tidus", "Noctis"),
    ("¿Quién es el antagonista principal de Final Fantasy VII?", "Sephiroth", "Kefka", "Seymour", "Ardyn"),
    ("¿Qué estudio desarrolló The Witcher 3?", "CD Projekt Red", "Bethesda", "BioWare", "Ubisoft"),
    ("¿Cómo se llama el protagonista de The Witcher?", "Geralt de Rivia", "Aloy", "Kratos", "Ezio Auditore"),
    ("¿Cómo se llama el protagonista de God of War?", "Kratos", "Atreus", "Zeus", "Ares"),
    ("¿Quién es la protagonista de Horizon Zero Dawn?", "Aloy", "Ellie", "Lara Croft", "Samus Aran"),
    ("¿Quién es la protagonista de la saga Metroid?", "Samus Aran", "Lara Croft", "Chun-Li", "Jill Valentine"),
    ("¿Cómo se llama el protagonista de Uncharted?", "Nathan Drake", "Joel Miller", "Leon S. Kennedy", "Ethan Winters"),
    ("¿Qué juego tiene la frase 'Un hombre elige, un esclavo obedece'?", "BioShock", "Fallout", "Half-Life", "Portal"),
    ("¿En qué juego se dice 'el pastel es una mentira'?", "Portal", "Half-Life", "BioShock", "Left 4 Dead"),
    ("¿Cómo se llama la IA villana de Portal?", "GLaDOS", "SHODAN", "HAL 9000", "Cortana"),
    ("¿Cómo se llama el protagonista de Half-Life?", "Gordon Freeman", "Alyx Vance", "Barney Calhoun", "Adrian Shephard"),
    ("¿Qué empresa creó Counter-Strike y Dota 2?", "Valve", "Riot Games", "Blizzard", "Ubisoft"),
    ("¿Qué compañía creó League of Legends?", "Riot Games", "Blizzard", "Valve", "Epic Games"),
    ("¿Qué compañía creó Overwatch?", "Blizzard", "Riot Games", "Valve", "Electronic Arts"),
    ("¿Cuál es el MMORPG más famoso de Blizzard?", "World of Warcraft", "Diablo", "StarCraft", "Hearthstone"),
    ("¿Qué juego tiene la frase 'Es peligroso ir solo, toma esto'?", "The Legend of Zelda", "Final Fantasy", "Dragon Quest", "Metroid"),
    ("¿Cómo se llama el reino donde transcurre Zelda?", "Hyrule", "Reino Champiñón", "Midgar", "Azeroth"),
    ("¿Cómo se llama el villano principal de Zelda?", "Ganondorf", "Bowser", "Vaati", "Zant"),
    ("¿Cómo se llama el hermano de Mario?", "Luigi", "Wario", "Waluigi", "Toad"),
    ("¿Qué debe comer Pac-Man para poder atrapar a los fantasmas?", "Píldoras de poder", "Cerezas", "Hongos", "Estrellas"),
    ("¿Cómo se llaman los fantasmas de Pac-Man?", "Blinky, Pinky, Inky y Clyde", "Blinky, Pinky, Inky y Sue", "Boo, Pinky, Inky y Clyde", "Blinky, Peach, Inky y Clyde"),
    ("¿En qué juego existe la ciudad de Los Santos?", "GTA V", "Saints Row", "Watch Dogs", "Mafia"),
    ("¿Qué estudio desarrolla la saga GTA?", "Rockstar Games", "Ubisoft", "Electronic Arts", "Square Enix"),
    ("¿En qué juego aparecen los Piglins?", "Minecraft", "Terraria", "Roblox", "Stardew Valley"),
    ("¿Cómo se llama la dimensión de lava y fortalezas de Minecraft?", "Nether", "End", "Superficie", "Aether"),
    ("¿Cómo se llama el jefe final de Minecraft?", "Ender Dragon", "Wither", "Warden", "Guardián Anciano"),
    ("¿Cómo se llama el protagonista de Skyrim?", "Dovahkiin", "Geralt", "Aloy", "Corvo"),
    ("¿Qué estudio desarrolló Skyrim?", "Bethesda", "CD Projekt", "Obsidian", "BioWare"),
    ("¿Qué mascota es Vault Boy?", "Fallout", "Skyrim", "Borderlands", "Doom"),
    ("¿Cómo se llama el protagonista de DOOM (2016)?", "Doom Slayer", "Jefe Maestro", "Duke Nukem", "Gordon Freeman"),
    ("¿Qué mensaje aparece al morir en Dark Souls?", "YOU DIED", "GAME OVER", "WASTED", "MISSION FAILED"),
    ("¿Qué estudio desarrolló Dark Souls?", "FromSoftware", "Capcom", "Square Enix", "Bandai Namco"),
    ("¿En qué juego de FromSoftware aparece Malenia?", "Elden Ring", "Sekiro", "Bloodborne", "Dark Souls III"),
    ("¿Quién es el protagonista de Resident Evil 4?", "Leon S. Kennedy", "Chris Redfield", "Jill Valentine", "Ethan Winters"),
    ("¿Qué empresa creó Resident Evil?", "Capcom", "Konami", "Sega", "Namco"),
    ("¿Cómo se llama el protagonista de Metal Gear Solid?", "Solid Snake", "Big Boss", "Raiden", "Otacon"),
    ("¿Quién es el creador de Metal Gear?", "Hideo Kojima", "Shigeru Miyamoto", "Hidetaka Miyazaki", "Toru Iwatani"),
    ("¿Quién creó a Mario?", "Shigeru Miyamoto", "Satoru Iwata", "Hideo Kojima", "Gunpei Yokoi"),
    ("¿Qué consola lanzó Sony en 1994?", "PlayStation", "Nintendo 64", "Sega Saturn", "Dreamcast"),
    ("¿Qué consola de Nintendo se lanzó en 2006 con control de movimiento?", "Wii", "GameCube", "Wii U", "Switch"),
    ("¿Qué consola lanzó Nintendo en 2017?", "Switch", "Wii U", "3DS", "GameCube"),
    ("¿Qué compañía fabrica la consola Xbox?", "Microsoft", "Sony", "Nintendo", "Sega"),
    ("¿Cuál fue la última consola de Sega?", "Dreamcast", "Saturn", "Genesis", "Game Gear"),
    ("¿Qué juego popularizó el género Battle Royale en 2017 con la isla Erangel?", "PUBG", "Fortnite", "Apex Legends", "Warzone"),
    ("¿Cuál es el Pokémon número 25 de la Pokédex?", "Pikachu", "Raichu", "Pichu", "Jigglypuff"),
    ("¿Cuántos tipos de Pokémon existen?", "18", "15", "17", "20"),
    ("¿En qué evoluciona Charmander?", "Charmeleon", "Charizard", "Charjabug", "Charcadet"),
    ("¿Cómo se llama el profesor Pokémon de Kanto?", "Profesor Oak", "Profesor Elm", "Profesor Birch", "Profesor Rowan"),
    ("¿Qué Pokémon legendario es un clon de Mew?", "Mewtwo", "Deoxys", "Genesect", "Lugia"),
    ("¿Cómo se llama la ciudad del primer gimnasio de Pokémon Rojo y Azul?", "Ciudad Plateada", "Ciudad Celeste", "Ciudad Carmín", "Ciudad Azulona"),
    ("¿Cómo se llama el dinosaurio verde compañero de Mario?", "Yoshi", "Rex", "Bowser", "Toad"),
    ("¿Cómo se llama la bolita rosa protagonista de Nintendo?", "Kirby", "Jigglypuff", "Pac-Man", "Puyo"),
    ("¿Quién es el villano recurrente de Kirby con un mazo?", "Rey Dedede", "Meta Knight", "Marx", "Magolor"),
    ("¿Quién creó Tetris?", "Alexey Pajitnov", "Shigeru Miyamoto", "Toru Iwatani", "Satoru Iwata"),
    ("¿Qué personajes jugables tiene Minecraft por defecto?", "Steve y Alex", "Mario y Luigi", "Sonic y Tails", "Link y Zelda"),
    ("¿Cómo se llama el rol que mata a la tripulación en Among Us?", "Impostor", "Asesino", "Traidor", "Lobo"),
    ("¿Qué estudio desarrolló Among Us?", "Innersloth", "Mojang", "Valve", "Supercell"),
    ("¿Quién creó Stardew Valley?", "ConcernedApe", "Toby Fox", "Team Cherry", "Mojang"),
    ("¿Quién creó Undertale?", "Toby Fox", "ConcernedApe", "Team Cherry", "Edmund McMillen"),
    ("¿Cómo se llama el protagonista humano de Undertale?", "Frisk", "Asriel", "Sans", "Flowey"),
    ("¿Qué metroidvania de insectos creó Team Cherry?", "Hollow Knight", "Ori", "Celeste", "Dead Cells"),
    ("¿Cómo se llama la protagonista de Celeste?", "Madeline", "Maddie", "Marie", "Mia"),
    ("¿Quién es el protagonista de Hades, de Supergiant Games?", "Zagreus", "Kratos", "Orfeo", "Aquiles"),
    ("¿Cómo se llama el dragón que amenaza el mundo en Skyrim?", "Alduin", "Paarthurnax", "Odahviing", "Smaug"),
    ("¿Qué compañía creó Fortnite?", "Epic Games", "Valve", "Activision", "Riot Games"),
    ("¿Qué saga tiene los modos Zombis y Warzone?", "Call of Duty", "Battlefield", "Halo", "Far Cry"),
    ("¿Qué compañía publica Call of Duty?", "Activision", "Electronic Arts", "Ubisoft", "Sony"),
    ("¿Cómo se llama el protagonista de Assassin's Creed II?", "Ezio Auditore", "Altaïr", "Connor", "Edward Kenway"),
    ("¿Quién es el protagonista de Red Dead Redemption 2?", "Arthur Morgan", "John Marston", "Dutch van der Linde", "Micah Bell"),
    ("¿Cómo se llama la ciudad de GTA IV?", "Liberty City", "Vice City", "San Andreas", "Los Santos"),
    ("¿Qué juego de Zelda de 2017 tiene un mundo abierto?", "Breath of the Wild", "Ocarina of Time", "Majora's Mask", "Skyward Sword"),
    ("¿Cuál es la secuela de Breath of the Wild?", "Tears of the Kingdom", "Skyward Sword", "Twilight Princess", "Wind Waker"),
    ("¿Cuál es el nombre en clave del protagonista de Persona 5?", "Joker", "Skull", "Panther", "Fox"),
    ("¿Qué juego tiene a Tidus y Yuna?", "Final Fantasy X", "Final Fantasy VII", "Final Fantasy VIII", "Final Fantasy IX"),
    ("¿Qué saga de RPG es famosa por sus slimes?", "Dragon Quest", "Final Fantasy", "Chrono Trigger", "Kingdom Hearts"),
    ("¿Qué saga combina personajes de Disney con Final Fantasy?", "Kingdom Hearts", "Chrono Cross", "Xenoblade", "Bravely Default"),
    ("¿Cómo se llama el protagonista de Kingdom Hearts?", "Sora", "Riku", "Roxas", "Kairi"),
    ("¿Qué hero shooter táctico lanzó Riot Games en 2020?", "Valorant", "Overwatch", "Apex Legends", "Counter-Strike 2"),
    ("¿Qué juego de peleas de Capcom tiene a Ryu y Ken?", "Street Fighter", "Tekken", "Mortal Kombat", "Soulcalibur"),
    ("¿Qué personaje de Mortal Kombat dice 'Get over here!'?", "Scorpion", "Sub-Zero", "Raiden", "Liu Kang"),
    ("¿Qué juego de peleas tiene al clan Mishima?", "Tekken", "Street Fighter", "Soulcalibur", "King of Fighters"),
    ("¿Qué compañía creó Super Smash Bros.?", "Nintendo", "Sega", "Capcom", "Bandai Namco"),
    ("¿Cuál fue el primer videojuego comercial de éxito, un juego de ping pong de 1972?", "Pong", "Space Invaders", "Pac-Man", "Asteroids"),
    ("¿Qué juego de 1978 tiene alienígenas que descienden por la pantalla?", "Space Invaders", "Galaga", "Pong", "Donkey Kong"),
    ("¿Cómo se llamaba Mario en el Donkey Kong original de 1981?", "Jumpman", "Mr. Video", "El Fontanero", "Luigi"),
]

ANIME += [
    ("¿Cómo se llama el protagonista de Hunter x Hunter?", "Gon Freecss", "Killua Zoldyck", "Kurapika", "Hisoka"),
    ("¿Qué personaje de Hunter x Hunter es un mago con aspecto de payaso que ama pelear?", "Hisoka", "Chrollo Lucilfer", "Illumi Zoldyck", "Feitan"),
]

HISTORIA += [
    ("¿Qué filósofo griego fue condenado a beber cicuta?", "Sócrates", "Platón", "Aristóteles", "Diógenes"),
]

VIDEOJUEGOS += [
    ("¿Cómo se llama el héroe de la saga Mega Man?", "Mega Man", "Ryu", "Simon Belmont", "Samus Aran"),
    ("¿Qué estudio creó Fallout 3 y Starfield?", "Bethesda", "Obsidian", "Interplay", "inXile"),
]

TRIVIA = {
    "anime": ANIME,
    "historia": HISTORIA,
    "videojuegos": VIDEOJUEGOS,
}

# Palabras para "Adivina la palabra" (sin tildes ni espacios)
PALABRAS = {
    "anime": [
        "NARUTO", "GOKU", "LUFFY", "PIKACHU", "SAKURA", "TOTORO", "EVANGELION", "BLEACH", "ZORO", "NEZUKO",
        "TANJIRO", "SASUKE", "KAKASHI", "GOJO", "SUKUNA", "DENJI", "SAITAMA", "KIRITO", "KILLUA", "MIKASA",
        "LEVI", "EDWARD", "ALPHONSE", "GHIBLI", "SHINIGAMI", "HOKAGE", "SAIYAJIN", "KATANA", "AKATSUKI", "MANGA",
        "OTAKU", "SENSEI", "KAWAII", "TITAN", "NINJA", "SAMURAI", "SHONEN", "ANYA", "POCHITA", "VEGETA",
    ],
    "historia": [
        "PIRAMIDES", "NAPOLEON", "REVOLUCION", "FARAON", "CLEOPATRA", "VIKINGO", "GUILLOTINA", "COLON", "MAGALLANES", "CORTES",
        "PIZARRO", "BOLIVAR", "INDEPENDENCIA", "IMPERIO", "MEDIEVAL", "CASTILLO", "CRUZADAS", "FEUDALISMO", "RENACIMIENTO", "GUERRA",
        "TRATADO", "DICTADURA", "DEMOCRACIA", "REPUBLICA", "MONARQUIA", "ALEJANDRO", "ESPARTA", "ATENAS", "PARTENON", "COLISEO",
        "GLADIADOR", "INCA", "AZTECA", "MAYA", "MURALLA", "JEROGLIFICO", "ARMADURA", "GALEON", "PERGAMINO", "ACUEDUCTO",
    ],
    "videojuegos": [
        "MARIO", "LUIGI", "ZELDA", "SONIC", "MINECRAFT", "FORTNITE", "POKEMON", "KIRBY", "PACMAN", "TETRIS",
        "CREEPER", "SKYRIM", "FALLOUT", "HALO", "KRATOS", "DOOM", "PORTAL", "CELESTE", "UNDERTALE", "VALORANT",
        "OVERWATCH", "NINTENDO", "PLAYSTATION", "XBOX", "SEGA", "CAPCOM", "CONSOLA", "JOYSTICK", "ARCADE", "NIVEL",
        "JEFE", "MISION", "PERSONAJE", "MULTIJUGADOR", "EXPERIENCIA", "LOGRO", "SPEEDRUN", "GAMER", "CHECKPOINT", "TROFEO",
    ],
}